language: node_js
sudo: false
node_js:
  - 6
env:
  global:
    # GITHUB_TOKEN
    - secure: m+kErh8rjqm5TIt+AM6zZB3Qx0zQuJnQRp3Fr3AECPOouCoVyGCf3j04/ZnAvZCqiNyuXihhG4PuMNeTIiC4fN/494HKF9le0GG2f1PcyKGBmOk1b6TLaUFIhR34WLztBSrwdEy8FoB1OzLg9BY2QOeF+5n2MBOef3nXkxDNNh1yC6I0PY3vTCwt4/aDUgGyy8rAYYioJ6d23+v4B2s8+RFVJxEqZd59bHpi6I0APlYDzrDiPMsPsZ9mT/KsxyCOYpfGIiFz2JHJfcSBz3exGw4Lt3tLltnycvss+6TyBfB022sBgbgEecfe7fXyMtckYrGBZWrSBa6/puXNfuK83HCqLJfh48Qed9KaQ2zOTIqYxjvXWWSyruuOnycBWQ2fhzmqX7sBF+pDa1j9kCIxXZbDbt7RjZhi42gTtUgAbzy+iNzTnG1QqkDfBmK27y0IMPDHuHnpR1qhm+g0jfYd2Dm7MKHIiu8yASGwyG3Z4ZvwEA4fZ98Qm0oPd9XJvhacVLob9NNMNNSi1pg1QLNQ7RQb27JFVfxZcRa0w935L7SOl/CgD0qnCjSmEigYHP+siN4QgmBGaI2ygt6dNvYPi41HyzgEIuKBHS3Nnoxh0lBKdIIMRAtfTHVs0JYUPjVPlTtTJWMa+NBQV+G9SmVss1WC3Hc4016CAELMkdmPTjo=
    - NPM_CONFIG_PROGRESS="false"
cache:
  directories:
    - node_modules
before_script:
  - git submodule foreach git pull origin master
before_install:
  - npm prune
script:
  - 'npm run lint && npm run build'
before_deploy:
  - 'git config --global user.email "gh-pages@localhost"'
  - 'git config --global user.name "npm gh-pages"'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  'on':
    branch: master
